# .github/release.yml

on:
  push:
    branches:
      - master
  jobs:
    changelog:
      exclude:
        labels:
          - ignore-for-release
        authors:
          - octocat
      categories:
        - title: Breaking Changes 🛠
          labels:
            - Semver-Major
            - breaking-change
        - title: Exciting New Features 🎉
          labels:
            - Semver-Minor
            - enhancement
        - title: Other Changes
          labels:
            - "*"
